name: PR Body Validator

on:
  pull_request:
    types: [opened, edited]  # Trigger on PR creation and editing

jobs:
  pr-body-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
#        with:
#          ref: masters

      - name: Log event action
        run: echo "event type is:" ${{ github.event.action }}

      - name: Run custom check
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: kotlinc -script ./PRBodyCheck.main.kts "${{g}"