name: PR Check

on:
  pull_request:
    types: [opened, edited]  # Trigger on PR creation and editing


jobs:
  pr-body-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PR body has changed
        id: check_body
        run: |
          # Fetch the previous PR body
          PREVIOUS_BODY=$(jq -r .pull_request.body < $GITHUB_EVENT_PATH)
          
          # Fetch the current PR body
          CURRENT_BODY="${{ github.event.pull_request.body }}"
          
          # Compare the bodies
          if [ "$PREVIOUS_BODY" != "$CURRENT_BODY" ]; then
          echo "PR body has changed."
          echo "changed=true" >> $GITHUB_ENV
          else
          echo "PR body has not changed."
          echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Run custom check if body changed
        if: env.changed == 'true'
        run: kotlinc -script ./PRBodyCheck.main.kts