name: PR Body Validator

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Run custom check
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: kotlinc -script ./PRBodyCheck.main.kts