name: PR Check

on:
  pull_request:
    types: [opened, edited]  # Trigger on PR creation and editing


jobs:
  pr-body-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Kotlin script
        run: kotlinc -script ./PRBodyCheck.main.kts